# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1081, 638)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 951, 571))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelRoutine = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.labelRoutine.setReadOnly(True)
        self.labelRoutine.setObjectName(_fromUtf8("labelRoutine"))
        self.horizontalLayout_2.addWidget(self.labelRoutine)
        self.labelStatus = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.labelStatus.setReadOnly(True)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.horizontalLayout_2.addWidget(self.labelStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listRoutines = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.listRoutines.setObjectName(_fromUtf8("listRoutines"))
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        self.horizontalLayout_3.addWidget(self.listRoutines)
        self.listRoutineStatus = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.listRoutineStatus.setEnabled(False)
        self.listRoutineStatus.setObjectName(_fromUtf8("listRoutineStatus"))
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        self.horizontalLayout_3.addWidget(self.listRoutineStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabRoutineSetup = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabRoutineSetup.setObjectName(_fromUtf8("tabRoutineSetup"))
        self.tabRtn0Setup = QtGui.QWidget()
        self.tabRtn0Setup.setObjectName(_fromUtf8("tabRtn0Setup"))
        self.btnRtn0Start = QtGui.QPushButton(self.tabRtn0Setup)
        self.btnRtn0Start.setGeometry(QtCore.QRect(240, 10, 61, 20))
        self.btnRtn0Start.setObjectName(_fromUtf8("btnRtn0Start"))
        self.lblRtn0SetupStatus = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lblRtn0SetupStatus.setGeometry(QtCore.QRect(10, 10, 231, 20))
        self.lblRtn0SetupStatus.setReadOnly(True)
        self.lblRtn0SetupStatus.setObjectName(_fromUtf8("lblRtn0SetupStatus"))
        self.lineEdit = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit.setGeometry(QtCore.QRect(10, 41, 91, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 81, 91, 20))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 101, 91, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.sbRtn0NumPoints = QtGui.QSpinBox(self.tabRtn0Setup)
        self.sbRtn0NumPoints.setGeometry(QtCore.QRect(100, 41, 91, 20))
        self.sbRtn0NumPoints.setMinimum(0)
        self.sbRtn0NumPoints.setMaximum(10000)
        self.sbRtn0NumPoints.setProperty("value", 200)
        self.sbRtn0NumPoints.setObjectName(_fromUtf8("sbRtn0NumPoints"))
        self.sbRtn0XInitial = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0XInitial.setGeometry(QtCore.QRect(100, 81, 91, 20))
        self.sbRtn0XInitial.setMinimum(-65535.0)
        self.sbRtn0XInitial.setMaximum(65536.0)
        self.sbRtn0XInitial.setObjectName(_fromUtf8("sbRtn0XInitial"))
        self.sbRtn0XFinal = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0XFinal.setGeometry(QtCore.QRect(100, 101, 91, 21))
        self.sbRtn0XFinal.setMinimum(-65535.0)
        self.sbRtn0XFinal.setMaximum(65536.0)
        self.sbRtn0XFinal.setProperty("value", 1.0)
        self.sbRtn0XFinal.setObjectName(_fromUtf8("sbRtn0XFinal"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 61, 91, 20))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.sbRtn0StepDelay = QtGui.QSpinBox(self.tabRtn0Setup)
        self.sbRtn0StepDelay.setGeometry(QtCore.QRect(100, 61, 91, 20))
        self.sbRtn0StepDelay.setMinimum(-1)
        self.sbRtn0StepDelay.setMaximum(1000)
        self.sbRtn0StepDelay.setProperty("value", 50)
        self.sbRtn0StepDelay.setObjectName(_fromUtf8("sbRtn0StepDelay"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 160, 51, 20))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 180, 251, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 200, 21, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 220, 21, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 240, 21, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.sbRtn0G1a = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G1a.setGeometry(QtCore.QRect(30, 200, 101, 21))
        self.sbRtn0G1a.setMinimum(-255.0)
        self.sbRtn0G1a.setMaximum(256.0)
        self.sbRtn0G1a.setObjectName(_fromUtf8("sbRtn0G1a"))
        self.sbRtn0G1b = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G1b.setGeometry(QtCore.QRect(30, 220, 101, 21))
        self.sbRtn0G1b.setMinimum(-255.0)
        self.sbRtn0G1b.setMaximum(256.0)
        self.sbRtn0G1b.setProperty("value", 3.0)
        self.sbRtn0G1b.setObjectName(_fromUtf8("sbRtn0G1b"))
        self.sbRtn0G1c = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G1c.setGeometry(QtCore.QRect(30, 240, 101, 21))
        self.sbRtn0G1c.setMinimum(-255.0)
        self.sbRtn0G1c.setMaximum(256.0)
        self.sbRtn0G1c.setProperty("value", -2.0)
        self.sbRtn0G1c.setObjectName(_fromUtf8("sbRtn0G1c"))
        self.sbRtn0G1d = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G1d.setGeometry(QtCore.QRect(160, 200, 101, 21))
        self.sbRtn0G1d.setMinimum(-255.0)
        self.sbRtn0G1d.setMaximum(256.0)
        self.sbRtn0G1d.setProperty("value", 0.3)
        self.sbRtn0G1d.setObjectName(_fromUtf8("sbRtn0G1d"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 240, 21, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.sbRtn0G1e = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G1e.setGeometry(QtCore.QRect(160, 220, 101, 21))
        self.sbRtn0G1e.setMinimum(-255.0)
        self.sbRtn0G1e.setMaximum(256.0)
        self.sbRtn0G1e.setObjectName(_fromUtf8("sbRtn0G1e"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 200, 21, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.sbRtn0G1f = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G1f.setGeometry(QtCore.QRect(160, 240, 101, 21))
        self.sbRtn0G1f.setMinimum(-255.0)
        self.sbRtn0G1f.setMaximum(256.0)
        self.sbRtn0G1f.setProperty("value", -0.1)
        self.sbRtn0G1f.setObjectName(_fromUtf8("sbRtn0G1f"))
        self.lineEdit_13 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 220, 21, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 300, 51, 20))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 320, 251, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_16 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 340, 21, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.lineEdit_17 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 360, 21, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.sbRtn0G2a = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G2a.setGeometry(QtCore.QRect(30, 340, 91, 22))
        self.sbRtn0G2a.setMinimum(-255.0)
        self.sbRtn0G2a.setMaximum(256.0)
        self.sbRtn0G2a.setProperty("value", 1.0)
        self.sbRtn0G2a.setObjectName(_fromUtf8("sbRtn0G2a"))
        self.sbRtn0G2b = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G2b.setGeometry(QtCore.QRect(30, 360, 91, 22))
        self.sbRtn0G2b.setMinimum(-255.0)
        self.sbRtn0G2b.setMaximum(256.0)
        self.sbRtn0G2b.setProperty("value", 3.0)
        self.sbRtn0G2b.setObjectName(_fromUtf8("sbRtn0G2b"))
        self.sbRtn0G2c = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G2c.setGeometry(QtCore.QRect(170, 340, 91, 22))
        self.sbRtn0G2c.setMinimum(-255.0)
        self.sbRtn0G2c.setMaximum(256.0)
        self.sbRtn0G2c.setProperty("value", 0.5)
        self.sbRtn0G2c.setObjectName(_fromUtf8("sbRtn0G2c"))
        self.sbRtn0G2d = QtGui.QDoubleSpinBox(self.tabRtn0Setup)
        self.sbRtn0G2d.setGeometry(QtCore.QRect(170, 360, 91, 22))
        self.sbRtn0G2d.setMinimum(-255.0)
        self.sbRtn0G2d.setMaximum(256.0)
        self.sbRtn0G2d.setProperty("value", 5.0)
        self.sbRtn0G2d.setObjectName(_fromUtf8("sbRtn0G2d"))
        self.lineEdit_18 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_18.setGeometry(QtCore.QRect(150, 340, 21, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_19 = QtGui.QLineEdit(self.tabRtn0Setup)
        self.lineEdit_19.setGeometry(QtCore.QRect(150, 360, 21, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.tabRoutineSetup.addTab(self.tabRtn0Setup, _fromUtf8(""))
        self.tabRtn1Setup = QtGui.QWidget()
        self.tabRtn1Setup.setObjectName(_fromUtf8("tabRtn1Setup"))
        self.tabRoutineSetup.addTab(self.tabRtn1Setup, _fromUtf8(""))
        self.tabRtn2Setup = QtGui.QWidget()
        self.tabRtn2Setup.setObjectName(_fromUtf8("tabRtn2Setup"))
        self.tabRoutineSetup.addTab(self.tabRtn2Setup, _fromUtf8(""))
        self.tabRtn3Setup = QtGui.QWidget()
        self.tabRtn3Setup.setObjectName(_fromUtf8("tabRtn3Setup"))
        self.tabRoutineSetup.addTab(self.tabRtn3Setup, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabRoutineSetup)
        self.tabRoutinePerform = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabRoutinePerform.setDocumentMode(False)
        self.tabRoutinePerform.setObjectName(_fromUtf8("tabRoutinePerform"))
        self.tabRtn0Run = QtGui.QWidget()
        self.tabRtn0Run.setObjectName(_fromUtf8("tabRtn0Run"))
        self.btnRtn0Pause = QtGui.QPushButton(self.tabRtn0Run)
        self.btnRtn0Pause.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.btnRtn0Pause.setObjectName(_fromUtf8("btnRtn0Pause"))
        self.btnRtn0Resume = QtGui.QPushButton(self.tabRtn0Run)
        self.btnRtn0Resume.setGeometry(QtCore.QRect(60, 60, 51, 21))
        self.btnRtn0Resume.setObjectName(_fromUtf8("btnRtn0Resume"))
        self.btnRtn0Cancel = QtGui.QPushButton(self.tabRtn0Run)
        self.btnRtn0Cancel.setGeometry(QtCore.QRect(160, 60, 51, 21))
        self.btnRtn0Cancel.setObjectName(_fromUtf8("btnRtn0Cancel"))
        self.pbRtn0 = QtGui.QProgressBar(self.tabRtn0Run)
        self.pbRtn0.setGeometry(QtCore.QRect(10, 10, 241, 23))
        self.pbRtn0.setProperty("value", 0)
        self.pbRtn0.setInvertedAppearance(False)
        self.pbRtn0.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.pbRtn0.setObjectName(_fromUtf8("pbRtn0"))
        self.lblRtn0Status = QtGui.QLineEdit(self.tabRtn0Run)
        self.lblRtn0Status.setGeometry(QtCore.QRect(10, 30, 206, 21))
        self.lblRtn0Status.setReadOnly(True)
        self.lblRtn0Status.setObjectName(_fromUtf8("lblRtn0Status"))
        self.gvRtn0Graph1 = QtGui.QGraphicsView(self.tabRtn0Run)
        self.gvRtn0Graph1.setGeometry(QtCore.QRect(20, 110, 391, 181))
        self.gvRtn0Graph1.setObjectName(_fromUtf8("gvRtn0Graph1"))
        self.gvRtn0Graph2 = QtGui.QGraphicsView(self.tabRtn0Run)
        self.gvRtn0Graph2.setGeometry(QtCore.QRect(20, 340, 391, 181))
        self.gvRtn0Graph2.setObjectName(_fromUtf8("gvRtn0Graph2"))
        self.label = QtGui.QLabel(self.tabRtn0Run)
        self.label.setGeometry(QtCore.QRect(180, 90, 47, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabRtn0Run)
        self.label_2.setGeometry(QtCore.QRect(190, 320, 47, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabRoutinePerform.addTab(self.tabRtn0Run, _fromUtf8(""))
        self.tabRtn1Run = QtGui.QWidget()
        self.tabRtn1Run.setObjectName(_fromUtf8("tabRtn1Run"))
        self.tabRoutinePerform.addTab(self.tabRtn1Run, _fromUtf8(""))
        self.tabRtn2Run = QtGui.QWidget()
        self.tabRtn2Run.setObjectName(_fromUtf8("tabRtn2Run"))
        self.tabRoutinePerform.addTab(self.tabRtn2Run, _fromUtf8(""))
        self.tabRtn3Run = QtGui.QWidget()
        self.tabRtn3Run.setObjectName(_fromUtf8("tabRtn3Run"))
        self.tabRoutinePerform.addTab(self.tabRtn3Run, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabRoutinePerform)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listRoutines.setCurrentRow(0)
        self.tabRoutineSetup.setCurrentIndex(0)
        self.tabRoutinePerform.setCurrentIndex(0)
        QtCore.QObject.connect(self.listRoutines, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.tabRoutinePerform.setCurrentIndex)
        QtCore.QObject.connect(self.listRoutines, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.tabRoutineSetup.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelRoutine.setText(_translate("MainWindow", "Routine", None))
        self.labelStatus.setText(_translate("MainWindow", "Status", None))
        __sortingEnabled = self.listRoutines.isSortingEnabled()
        self.listRoutines.setSortingEnabled(False)
        item = self.listRoutines.item(0)
        item.setText(_translate("MainWindow", "Test Routine", None))
        item = self.listRoutines.item(1)
        item.setText(_translate("MainWindow", "Routine 1", None))
        item = self.listRoutines.item(2)
        item.setText(_translate("MainWindow", "Routine 2", None))
        item = self.listRoutines.item(3)
        item.setText(_translate("MainWindow", "Routine 3", None))
        self.listRoutines.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listRoutineStatus.isSortingEnabled()
        self.listRoutineStatus.setSortingEnabled(False)
        item = self.listRoutineStatus.item(0)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(1)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(2)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(3)
        item.setText(_translate("MainWindow", "Not checked", None))
        self.listRoutineStatus.setSortingEnabled(__sortingEnabled)
        self.btnRtn0Start.setText(_translate("MainWindow", "Start", None))
        self.lblRtn0SetupStatus.setPlaceholderText(_translate("MainWindow", "Setup status", None))
        self.lineEdit.setText(_translate("MainWindow", "Number of points", None))
        self.lineEdit_2.setText(_translate("MainWindow", "Initial X", None))
        self.lineEdit_3.setText(_translate("MainWindow", "Final X", None))
        self.lineEdit_4.setText(_translate("MainWindow", "Step delay (ms)", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Graph 1", None))
        self.lineEdit_6.setText(_translate("MainWindow", "Y = a + b*x + c*x^2 + d*x^3 + e*x^4 + f*x^5", None))
        self.lineEdit_7.setText(_translate("MainWindow", "a", None))
        self.lineEdit_8.setText(_translate("MainWindow", "b", None))
        self.lineEdit_9.setText(_translate("MainWindow", "c", None))
        self.lineEdit_11.setText(_translate("MainWindow", "f", None))
        self.lineEdit_12.setText(_translate("MainWindow", "d", None))
        self.lineEdit_13.setText(_translate("MainWindow", "e", None))
        self.lineEdit_14.setText(_translate("MainWindow", "Graph 2", None))
        self.lineEdit_15.setText(_translate("MainWindow", "Y = a*sin(b*2pi*x) + c*cos(d*2pi*x)", None))
        self.lineEdit_16.setText(_translate("MainWindow", "a", None))
        self.lineEdit_17.setText(_translate("MainWindow", "b", None))
        self.lineEdit_18.setText(_translate("MainWindow", "c", None))
        self.lineEdit_19.setText(_translate("MainWindow", "d", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn0Setup), _translate("MainWindow", "Dummy Routine", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn1Setup), _translate("MainWindow", "Routine 1", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn2Setup), _translate("MainWindow", "Rtn 2", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn3Setup), _translate("MainWindow", "Rtn 3", None))
        self.btnRtn0Pause.setText(_translate("MainWindow", "Pause", None))
        self.btnRtn0Resume.setText(_translate("MainWindow", "Resume", None))
        self.btnRtn0Cancel.setText(_translate("MainWindow", "Cancel", None))
        self.lblRtn0Status.setPlaceholderText(_translate("MainWindow", "steps done / steps total", None))
        self.label.setText(_translate("MainWindow", "Graph 1", None))
        self.label_2.setText(_translate("MainWindow", "Graph 2", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn0Run), _translate("MainWindow", "Dummy Routine", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn1Run), _translate("MainWindow", "Routine 1", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn2Run), _translate("MainWindow", "Rtn 2", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn3Run), _translate("MainWindow", "Rtn 3", None))

