# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testmainwindow_2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(855, 640)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 821, 571))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelRoutine = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.labelRoutine.setReadOnly(True)
        self.labelRoutine.setObjectName(_fromUtf8("labelRoutine"))
        self.horizontalLayout_2.addWidget(self.labelRoutine)
        self.labelStatus = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.labelStatus.setReadOnly(True)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.horizontalLayout_2.addWidget(self.labelStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listRoutines = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.listRoutines.setObjectName(_fromUtf8("listRoutines"))
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        self.horizontalLayout_3.addWidget(self.listRoutines)
        self.listRoutineStatus = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.listRoutineStatus.setEnabled(False)
        self.listRoutineStatus.setObjectName(_fromUtf8("listRoutineStatus"))
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        self.horizontalLayout_3.addWidget(self.listRoutineStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabRoutineSetup = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabRoutineSetup.setObjectName(_fromUtf8("tabRoutineSetup"))
        self.tabRtn1 = QtGui.QWidget()
        self.tabRtn1.setObjectName(_fromUtf8("tabRtn1"))
        self.comboBox = QtGui.QComboBox(self.tabRtn1)
        self.comboBox.setGeometry(QtCore.QRect(80, 10, 71, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.lineEdit = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 30, 71, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton = QtGui.QPushButton(self.tabRtn1)
        self.pushButton.setGeometry(QtCore.QRect(190, 10, 111, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 60, 111, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 210, 291, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 230, 151, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 250, 151, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 270, 151, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.comboBox_2 = QtGui.QComboBox(self.tabRtn1)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 251, 141, 21))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.lineEdit_9 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_9.setGeometry(QtCore.QRect(160, 230, 141, 21))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.spinBox = QtGui.QSpinBox(self.tabRtn1)
        self.spinBox.setGeometry(QtCore.QRect(160, 270, 141, 21))
        self.spinBox.setMaximum(4095)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tabRtn1)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 80, 291, 91))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.tabRoutineSetup.addTab(self.tabRtn1, _fromUtf8(""))
        self.tabRtn2 = QtGui.QWidget()
        self.tabRtn2.setObjectName(_fromUtf8("tabRtn2"))
        self.tabRoutineSetup.addTab(self.tabRtn2, _fromUtf8(""))
        self.tabRtn3 = QtGui.QWidget()
        self.tabRtn3.setObjectName(_fromUtf8("tabRtn3"))
        self.tabRoutineSetup.addTab(self.tabRtn3, _fromUtf8(""))
        self.tabRtn4 = QtGui.QWidget()
        self.tabRtn4.setObjectName(_fromUtf8("tabRtn4"))
        self.tabRoutineSetup.addTab(self.tabRtn4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabRoutineSetup)
        self.tabRoutinePerform = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabRoutinePerform.setDocumentMode(False)
        self.tabRoutinePerform.setObjectName(_fromUtf8("tabRoutinePerform"))
        self.tabRtn11 = QtGui.QWidget()
        self.tabRtn11.setObjectName(_fromUtf8("tabRtn11"))
        self.pushButton_2 = QtGui.QPushButton(self.tabRtn11)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tabRtn11)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 50, 51, 21))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tabRtn11)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 50, 51, 21))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.progressBar = QtGui.QProgressBar(self.tabRtn11)
        self.progressBar.setGeometry(QtCore.QRect(10, 10, 291, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.lineEdit_10 = QtGui.QLineEdit(self.tabRtn11)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 30, 291, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.graphicsView = QtGui.QGraphicsView(self.tabRtn11)
        self.graphicsView.setGeometry(QtCore.QRect(75, 90, 221, 192))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.label = QtGui.QLabel(self.tabRtn11)
        self.label.setGeometry(QtCore.QRect(170, 280, 31, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabRtn11)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 31, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabRoutinePerform.addTab(self.tabRtn11, _fromUtf8(""))
        self.tabRtn21 = QtGui.QWidget()
        self.tabRtn21.setObjectName(_fromUtf8("tabRtn21"))
        self.tabRoutinePerform.addTab(self.tabRtn21, _fromUtf8(""))
        self.tabRtn31 = QtGui.QWidget()
        self.tabRtn31.setObjectName(_fromUtf8("tabRtn31"))
        self.tabRoutinePerform.addTab(self.tabRtn31, _fromUtf8(""))
        self.tabRtn41 = QtGui.QWidget()
        self.tabRtn41.setObjectName(_fromUtf8("tabRtn41"))
        self.tabRoutinePerform.addTab(self.tabRtn41, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabRoutinePerform)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listRoutines.setCurrentRow(0)
        self.tabRoutineSetup.setCurrentIndex(0)
        self.tabRoutinePerform.setCurrentIndex(0)
        QtCore.QObject.connect(self.listRoutines, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.tabRoutineSetup.setCurrentIndex)
        QtCore.QObject.connect(self.listRoutines, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.tabRoutinePerform.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelRoutine.setText(_translate("MainWindow", "Routine", None))
        self.labelStatus.setText(_translate("MainWindow", "Status", None))
        __sortingEnabled = self.listRoutines.isSortingEnabled()
        self.listRoutines.setSortingEnabled(False)
        item = self.listRoutines.item(0)
        item.setText(_translate("MainWindow", "Routine 1", None))
        item = self.listRoutines.item(1)
        item.setText(_translate("MainWindow", "Routine 2", None))
        item = self.listRoutines.item(2)
        item.setText(_translate("MainWindow", "Routine 3", None))
        item = self.listRoutines.item(3)
        item.setText(_translate("MainWindow", "Routine 4", None))
        self.listRoutines.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listRoutineStatus.isSortingEnabled()
        self.listRoutineStatus.setSortingEnabled(False)
        item = self.listRoutineStatus.item(0)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(1)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(2)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(3)
        item.setText(_translate("MainWindow", "Not checked", None))
        self.listRoutineStatus.setSortingEnabled(__sortingEnabled)
        self.comboBox.setItemText(0, _translate("MainWindow", "Sensor", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Module", None))
        self.lineEdit.setText(_translate("MainWindow", "Part type", None))
        self.lineEdit_2.setText(_translate("MainWindow", "Part ID", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.pushButton.setText(_translate("MainWindow", "Select from Database", None))
        self.lineEdit_4.setText(_translate("MainWindow", "Selected part status", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Routine parameters", None))
        self.lineEdit_6.setText(_translate("MainWindow", "Parameter 1", None))
        self.lineEdit_7.setText(_translate("MainWindow", "Parameter 2", None))
        self.lineEdit_8.setText(_translate("MainWindow", "Parameter 3", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Option 1", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Option 2", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Option 3", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn1), _translate("MainWindow", "Routine 1", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn2), _translate("MainWindow", "Routine 2", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn3), _translate("MainWindow", "Rtn 3", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn4), _translate("MainWindow", "Rtn 4", None))
        self.pushButton_2.setText(_translate("MainWindow", "Pause", None))
        self.pushButton_3.setText(_translate("MainWindow", "Resume", None))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel", None))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "steps done / steps total", None))
        self.label.setText(_translate("MainWindow", "X axis", None))
        self.label_2.setText(_translate("MainWindow", "Y axis", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn11), _translate("MainWindow", "Routine 1", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn21), _translate("MainWindow", "Routine 2", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn31), _translate("MainWindow", "Rtn 3", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn41), _translate("MainWindow", "Rtn 4", None))

