# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1081, 638)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 951, 571))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelRoutine = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.labelRoutine.setReadOnly(True)
        self.labelRoutine.setObjectName(_fromUtf8("labelRoutine"))
        self.horizontalLayout_2.addWidget(self.labelRoutine)
        self.labelStatus = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.labelStatus.setReadOnly(True)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.horizontalLayout_2.addWidget(self.labelStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listRoutines = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.listRoutines.setObjectName(_fromUtf8("listRoutines"))
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutines.addItem(item)
        self.horizontalLayout_3.addWidget(self.listRoutines)
        self.listRoutineStatus = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.listRoutineStatus.setEnabled(False)
        self.listRoutineStatus.setObjectName(_fromUtf8("listRoutineStatus"))
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listRoutineStatus.addItem(item)
        self.horizontalLayout_3.addWidget(self.listRoutineStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabRoutineSetup = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabRoutineSetup.setObjectName(_fromUtf8("tabRoutineSetup"))
        self.tabRtn1 = QtGui.QWidget()
        self.tabRtn1.setObjectName(_fromUtf8("tabRtn1"))
        self.btnRtn1Start = QtGui.QPushButton(self.tabRtn1)
        self.btnRtn1Start.setGeometry(QtCore.QRect(240, 10, 61, 20))
        self.btnRtn1Start.setObjectName(_fromUtf8("btnRtn1Start"))
        self.lblRtn1SetupStatus = QtGui.QLineEdit(self.tabRtn1)
        self.lblRtn1SetupStatus.setGeometry(QtCore.QRect(10, 10, 231, 20))
        self.lblRtn1SetupStatus.setReadOnly(True)
        self.lblRtn1SetupStatus.setObjectName(_fromUtf8("lblRtn1SetupStatus"))
        self.lineEdit = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit.setGeometry(QtCore.QRect(10, 41, 91, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 81, 91, 20))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 101, 91, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.sbRtn1NumPoints = QtGui.QSpinBox(self.tabRtn1)
        self.sbRtn1NumPoints.setGeometry(QtCore.QRect(100, 41, 91, 20))
        self.sbRtn1NumPoints.setMinimum(0)
        self.sbRtn1NumPoints.setMaximum(10000)
        self.sbRtn1NumPoints.setProperty("value", 200)
        self.sbRtn1NumPoints.setObjectName(_fromUtf8("sbRtn1NumPoints"))
        self.sbRtn1XInitial = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1XInitial.setGeometry(QtCore.QRect(100, 81, 91, 20))
        self.sbRtn1XInitial.setMinimum(-65535.0)
        self.sbRtn1XInitial.setMaximum(65536.0)
        self.sbRtn1XInitial.setObjectName(_fromUtf8("sbRtn1XInitial"))
        self.sbRtn1XFinal = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1XFinal.setGeometry(QtCore.QRect(100, 101, 91, 21))
        self.sbRtn1XFinal.setMinimum(-65535.0)
        self.sbRtn1XFinal.setMaximum(65536.0)
        self.sbRtn1XFinal.setProperty("value", 1.0)
        self.sbRtn1XFinal.setObjectName(_fromUtf8("sbRtn1XFinal"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 61, 91, 20))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.sbRtn1StepDelay = QtGui.QSpinBox(self.tabRtn1)
        self.sbRtn1StepDelay.setGeometry(QtCore.QRect(100, 61, 91, 20))
        self.sbRtn1StepDelay.setMinimum(1)
        self.sbRtn1StepDelay.setMaximum(1000)
        self.sbRtn1StepDelay.setProperty("value", 50)
        self.sbRtn1StepDelay.setObjectName(_fromUtf8("sbRtn1StepDelay"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 160, 51, 20))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 180, 251, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 200, 21, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 220, 21, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 240, 21, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.sbRtn1G1a = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G1a.setGeometry(QtCore.QRect(30, 200, 101, 21))
        self.sbRtn1G1a.setMinimum(-255.0)
        self.sbRtn1G1a.setMaximum(256.0)
        self.sbRtn1G1a.setObjectName(_fromUtf8("sbRtn1G1a"))
        self.sbRtn1G1b = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G1b.setGeometry(QtCore.QRect(30, 220, 101, 21))
        self.sbRtn1G1b.setMinimum(-255.0)
        self.sbRtn1G1b.setMaximum(256.0)
        self.sbRtn1G1b.setProperty("value", 3.0)
        self.sbRtn1G1b.setObjectName(_fromUtf8("sbRtn1G1b"))
        self.sbRtn1G1c = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G1c.setGeometry(QtCore.QRect(30, 240, 101, 21))
        self.sbRtn1G1c.setMinimum(-255.0)
        self.sbRtn1G1c.setMaximum(256.0)
        self.sbRtn1G1c.setProperty("value", -2.0)
        self.sbRtn1G1c.setObjectName(_fromUtf8("sbRtn1G1c"))
        self.sbRtn1G1d = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G1d.setGeometry(QtCore.QRect(160, 200, 101, 21))
        self.sbRtn1G1d.setMinimum(-255.0)
        self.sbRtn1G1d.setMaximum(256.0)
        self.sbRtn1G1d.setProperty("value", 0.3)
        self.sbRtn1G1d.setObjectName(_fromUtf8("sbRtn1G1d"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 240, 21, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.sbRtn1G1e = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G1e.setGeometry(QtCore.QRect(160, 220, 101, 21))
        self.sbRtn1G1e.setMinimum(-255.0)
        self.sbRtn1G1e.setMaximum(256.0)
        self.sbRtn1G1e.setObjectName(_fromUtf8("sbRtn1G1e"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 200, 21, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.sbRtn1G1f = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G1f.setGeometry(QtCore.QRect(160, 240, 101, 21))
        self.sbRtn1G1f.setMinimum(-255.0)
        self.sbRtn1G1f.setMaximum(256.0)
        self.sbRtn1G1f.setProperty("value", -0.1)
        self.sbRtn1G1f.setObjectName(_fromUtf8("sbRtn1G1f"))
        self.lineEdit_13 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 220, 21, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 300, 51, 20))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 320, 251, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_16 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 340, 21, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.lineEdit_17 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 360, 21, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.sbRtn1G2a = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G2a.setGeometry(QtCore.QRect(30, 340, 91, 22))
        self.sbRtn1G2a.setMinimum(-255.0)
        self.sbRtn1G2a.setMaximum(256.0)
        self.sbRtn1G2a.setProperty("value", 1.0)
        self.sbRtn1G2a.setObjectName(_fromUtf8("sbRtn1G2a"))
        self.sbRtn1G2b = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G2b.setGeometry(QtCore.QRect(30, 360, 91, 22))
        self.sbRtn1G2b.setMinimum(-255.0)
        self.sbRtn1G2b.setMaximum(256.0)
        self.sbRtn1G2b.setProperty("value", 3.0)
        self.sbRtn1G2b.setObjectName(_fromUtf8("sbRtn1G2b"))
        self.sbRtn1G2c = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G2c.setGeometry(QtCore.QRect(170, 340, 91, 22))
        self.sbRtn1G2c.setMinimum(-255.0)
        self.sbRtn1G2c.setMaximum(256.0)
        self.sbRtn1G2c.setProperty("value", 0.5)
        self.sbRtn1G2c.setObjectName(_fromUtf8("sbRtn1G2c"))
        self.sbRtn1G2d = QtGui.QDoubleSpinBox(self.tabRtn1)
        self.sbRtn1G2d.setGeometry(QtCore.QRect(170, 360, 91, 22))
        self.sbRtn1G2d.setMinimum(-255.0)
        self.sbRtn1G2d.setMaximum(256.0)
        self.sbRtn1G2d.setProperty("value", 5.0)
        self.sbRtn1G2d.setObjectName(_fromUtf8("sbRtn1G2d"))
        self.lineEdit_18 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_18.setGeometry(QtCore.QRect(150, 340, 21, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_19 = QtGui.QLineEdit(self.tabRtn1)
        self.lineEdit_19.setGeometry(QtCore.QRect(150, 360, 21, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.tabRoutineSetup.addTab(self.tabRtn1, _fromUtf8(""))
        self.tabRtn2 = QtGui.QWidget()
        self.tabRtn2.setObjectName(_fromUtf8("tabRtn2"))
        self.tabRoutineSetup.addTab(self.tabRtn2, _fromUtf8(""))
        self.tabRtn3 = QtGui.QWidget()
        self.tabRtn3.setObjectName(_fromUtf8("tabRtn3"))
        self.tabRoutineSetup.addTab(self.tabRtn3, _fromUtf8(""))
        self.tabRtn4 = QtGui.QWidget()
        self.tabRtn4.setObjectName(_fromUtf8("tabRtn4"))
        self.tabRoutineSetup.addTab(self.tabRtn4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabRoutineSetup)
        self.tabRoutinePerform = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.tabRoutinePerform.setDocumentMode(False)
        self.tabRoutinePerform.setObjectName(_fromUtf8("tabRoutinePerform"))
        self.tabRtn11 = QtGui.QWidget()
        self.tabRtn11.setObjectName(_fromUtf8("tabRtn11"))
        self.pushButton_2 = QtGui.QPushButton(self.tabRtn11)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tabRtn11)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 60, 51, 21))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tabRtn11)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 60, 51, 21))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.progressBar = QtGui.QProgressBar(self.tabRtn11)
        self.progressBar.setGeometry(QtCore.QRect(10, 10, 241, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.lineEdit_10 = QtGui.QLineEdit(self.tabRtn11)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 30, 206, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.graphicsView = QtGui.QGraphicsView(self.tabRtn11)
        self.graphicsView.setGeometry(QtCore.QRect(20, 110, 391, 181))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.graphicsView_3 = QtGui.QGraphicsView(self.tabRtn11)
        self.graphicsView_3.setGeometry(QtCore.QRect(20, 340, 391, 181))
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.label = QtGui.QLabel(self.tabRtn11)
        self.label.setGeometry(QtCore.QRect(180, 90, 47, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabRtn11)
        self.label_2.setGeometry(QtCore.QRect(190, 320, 47, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabRoutinePerform.addTab(self.tabRtn11, _fromUtf8(""))
        self.tabRtn21 = QtGui.QWidget()
        self.tabRtn21.setObjectName(_fromUtf8("tabRtn21"))
        self.tabRoutinePerform.addTab(self.tabRtn21, _fromUtf8(""))
        self.tabRtn31 = QtGui.QWidget()
        self.tabRtn31.setObjectName(_fromUtf8("tabRtn31"))
        self.tabRoutinePerform.addTab(self.tabRtn31, _fromUtf8(""))
        self.tabRtn41 = QtGui.QWidget()
        self.tabRtn41.setObjectName(_fromUtf8("tabRtn41"))
        self.tabRoutinePerform.addTab(self.tabRtn41, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabRoutinePerform)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listRoutines.setCurrentRow(-1)
        self.tabRoutineSetup.setCurrentIndex(0)
        self.tabRoutinePerform.setCurrentIndex(0)
        QtCore.QObject.connect(self.listRoutines, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.tabRoutinePerform.setCurrentIndex)
        QtCore.QObject.connect(self.listRoutines, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.tabRoutineSetup.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelRoutine.setText(_translate("MainWindow", "Routine", None))
        self.labelStatus.setText(_translate("MainWindow", "Status", None))
        __sortingEnabled = self.listRoutines.isSortingEnabled()
        self.listRoutines.setSortingEnabled(False)
        item = self.listRoutines.item(0)
        item.setText(_translate("MainWindow", "Test Routine", None))
        item = self.listRoutines.item(1)
        item.setText(_translate("MainWindow", "Routine 2", None))
        item = self.listRoutines.item(2)
        item.setText(_translate("MainWindow", "Routine 3", None))
        item = self.listRoutines.item(3)
        item.setText(_translate("MainWindow", "Routine 4", None))
        self.listRoutines.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listRoutineStatus.isSortingEnabled()
        self.listRoutineStatus.setSortingEnabled(False)
        item = self.listRoutineStatus.item(0)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(1)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(2)
        item.setText(_translate("MainWindow", "Not checked", None))
        item = self.listRoutineStatus.item(3)
        item.setText(_translate("MainWindow", "Not checked", None))
        self.listRoutineStatus.setSortingEnabled(__sortingEnabled)
        self.btnRtn1Start.setText(_translate("MainWindow", "Start", None))
        self.lblRtn1SetupStatus.setPlaceholderText(_translate("MainWindow", "Setup status", None))
        self.lineEdit.setText(_translate("MainWindow", "Number of points", None))
        self.lineEdit_2.setText(_translate("MainWindow", "Initial X", None))
        self.lineEdit_3.setText(_translate("MainWindow", "Final X", None))
        self.lineEdit_4.setText(_translate("MainWindow", "Step delay (ms)", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Graph 1", None))
        self.lineEdit_6.setText(_translate("MainWindow", "Y = a + b*x + c*x^2 + d*x^3 + e*x^4 + f*x^5", None))
        self.lineEdit_7.setText(_translate("MainWindow", "a", None))
        self.lineEdit_8.setText(_translate("MainWindow", "b", None))
        self.lineEdit_9.setText(_translate("MainWindow", "c", None))
        self.lineEdit_11.setText(_translate("MainWindow", "f", None))
        self.lineEdit_12.setText(_translate("MainWindow", "d", None))
        self.lineEdit_13.setText(_translate("MainWindow", "e", None))
        self.lineEdit_14.setText(_translate("MainWindow", "Graph 2", None))
        self.lineEdit_15.setText(_translate("MainWindow", "Y = a*sin(b*2pi*x) + c*cos(d*2pi*x)", None))
        self.lineEdit_16.setText(_translate("MainWindow", "a", None))
        self.lineEdit_17.setText(_translate("MainWindow", "b", None))
        self.lineEdit_18.setText(_translate("MainWindow", "c", None))
        self.lineEdit_19.setText(_translate("MainWindow", "d", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn1), _translate("MainWindow", "Test Routine", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn2), _translate("MainWindow", "Routine 2", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn3), _translate("MainWindow", "Rtn 3", None))
        self.tabRoutineSetup.setTabText(self.tabRoutineSetup.indexOf(self.tabRtn4), _translate("MainWindow", "Rtn 4", None))
        self.pushButton_2.setText(_translate("MainWindow", "Pause", None))
        self.pushButton_3.setText(_translate("MainWindow", "Resume", None))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel", None))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "steps done / steps total", None))
        self.label.setText(_translate("MainWindow", "Graph 1", None))
        self.label_2.setText(_translate("MainWindow", "Graph 2", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn11), _translate("MainWindow", "Test Routine", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn21), _translate("MainWindow", "Routine 2", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn31), _translate("MainWindow", "Rtn 3", None))
        self.tabRoutinePerform.setTabText(self.tabRoutinePerform.indexOf(self.tabRtn41), _translate("MainWindow", "Rtn 4", None))

